### ISSUE TITLE
Change endpoint to api.doctape.com.

### ISSUE THREAD

**Issue by srijs** [doctape/passport-doctape#1]
Wrong endpoint. Please fix.

**Comment by srijs** [comment]
Nevermind.

**Comment by srijs** [comment]
The userProfile method uses the 'my.doctape.com' endpoint. This doesn't work.

```
Error: failed to serialize user into session
at pass (/Users/srijs/Repo/doctape-backup/node_modules/passport/lib/passport/index.js:267:19)
at Passport.serializeUser (/Users/srijs/Repo/doctape-backup/node_modules/passport/lib/passport/index.js:275:5)
at IncomingMessage.req.login.req.logIn (/Users/srijs/Repo/doctape-backup/node_modules/passport/lib/passport/http/request.js:43:29)
at Context.module.exports.delegate.success (/Users/srijs/Repo/doctape-backup/node_modules/passport/lib/passport/middleware/authenticate.js:194:13)
at Context.actions.success (/Users/srijs/Repo/doctape-backup/node_modules/passport/lib/passport/context/http/actions.js:21:25)
at verified (/Users/srijs/Repo/doctape-backup/node_modules/passport-doctape/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:133:18)
at Strategy._verify (/Users/srijs/Repo/doctape-backup/doctape-backup.js:11:5)
at OAuth2Strategy.authenticate.params.response_type (/Users/srijs/Repo/doctape-backup/node_modules/passport-doctape/node_modules/passport-oauth/lib/passport-oauth/strategies/oauth2.js:148:20)
at Strategy.userProfile (/Users/srijs/Repo/doctape-backup/node_modules/passport-doctape/lib/passport-doctape/strategy.js:93:7)
at passBackControl (/Users/srijs/Repo/doctape-backup/node_modules/passport-doctape/node_modules/passport-oauth/node_modules/oauth/lib/oauth2.js:107:9)
```
